# Generated by Django 2.2.12 on 2020-10-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SIZES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setSize', models.IntegerField(default=1000)),
                ('playlistSize', models.IntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='TIMELIMIT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeLimit', models.IntegerField(default=10)),
            ],
        ),
       migrations.AddField(
            model_name='sizes',
            name='GapSize',
            field=models.IntegerField(default=10),
        ),
    ]
