# Generated by Django 2.2.12 on 2020-10-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SIZES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setSize', models.IntegerField(default=1000)),
                ('playlistSize', models.IntegerField(default=50)),
            ],
        ),
    ]
