# Generated by Django 2.2.12 on 2020-10-31 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizes',
            name='GapSize',
            field=models.IntegerField(default=10),
        ),
    ]
