# Generated by Django 2.2.12 on 2020-10-25 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Algos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algoName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Playlists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlistName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songTitle', models.CharField(max_length=50)),
                ('songAlbum', models.CharField(default="Don't Know", max_length=50)),
                ('songSinger', models.CharField(default="Don't Know", max_length=50)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SongsInPlaylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlistId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluate.Playlists')),
                ('songId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluate.Songs')),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('R1', models.IntegerField(default=-1)),
                ('R2', models.IntegerField(default=-1)),
                ('R3', models.IntegerField(default=-1)),
                ('R4', models.IntegerField(default=-1)),
                ('R5', models.IntegerField(default=-1)),
                ('average1', models.FloatField(default=-1)),
                ('average2', models.FloatField(default=-1)),
                ('average3', models.FloatField(default=-1)),
                ('standardDeviation', models.FloatField(default=-1)),
                ('variance', models.FloatField(default=-1)),
                ('distributionScore', models.FloatField(default=-1)),
                ('correlationScore', models.FloatField(default=-1)),
                ('totalScore', models.FloatField(default=-1)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('algoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluate.Algos')),
                ('playlistId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluate.Playlists')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ordering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('ratingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluate.Ratings')),
                ('songId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluate.Songs')),
            ],
        ),
    ]
