# Generated by Django 3.1.2 on 2020-10-07 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Algos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algoName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Playlists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlistName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songTitle', models.CharField(max_length=50)),
                ('songAlbum', models.CharField(default="Don't Know", max_length=50)),
                ('songSinger', models.CharField(default="Don't Know", max_length=50)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SongsInPlaylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlistId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluate.playlists')),
                ('songId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluate.songs')),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('R1', models.IntegerField(default=-1)),
                ('R2', models.IntegerField(default=-1)),
                ('R3', models.IntegerField(default=-1)),
                ('R4', models.IntegerField(default=-1)),
                ('R5', models.IntegerField(default=-1)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('algoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluate.algos')),
                ('playlistId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluate.playlists')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
