# Generated by Django 2.2.12 on 2020-10-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='R10',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='ratings',
            name='R6',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='ratings',
            name='R7',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='ratings',
            name='R8',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='ratings',
            name='R9',
            field=models.IntegerField(default=-1),
        ),
    ]
