# Generated by Django 3.1.2 on 2020-10-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='average1',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='ratings',
            name='average2',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='ratings',
            name='average3',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='ratings',
            name='correlationScore',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='ratings',
            name='distributionScore',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='ratings',
            name='standardDeviation',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='ratings',
            name='variance',
            field=models.FloatField(default=-1),
        ),
    ]
