# Generated by Django 3.1.2 on 2020-10-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate', '0002_auto_20201009_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='totalScore',
            field=models.FloatField(default=-1),
        ),
    ]
