# Generated by Django 2.2.12 on 2020-10-21 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate', '0003_ratings_totalscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('ratingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluate.Ratings')),
                ('songId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluate.Songs')),
            ],
        ),
    ]
